### ISSUE TITLE
Support for line numbers

### ISSUE THREAD

**Issue by srenatus** [jaredpetersen/codeprinter#22]
Hi there.

This tool can be quite handy. However, for talking about printed code, line numbers would be very helpful. Is this feature already there and I just haven't found it?

Edit: [I guess there's no easy way here..](http://highlightjs.readthedocs.org/en/latest/line-numbers.html?highlight=numbers)

Thanks a lot
Stephan

**Comment by jaredpetersen** [comment]
Hi Stephen,

I agree, line numbers is a feature that I would love to have added. Unfortunately, there's a bit of a disconnect between the print document size, the code being printed, and where the lines are placed within that document. You think that you would be able to just count newline characters and put the line number next to each line of code, but text wrapping screws the whole thing up; A really long line that has a single newline character at the end would be counted as a single line but can actually take up several lines. 

One of the previous, non-working iterations of the program tried to split the input code into "words" through the use of some regular expression and placed each word in printed document line by line. I got very close, but I was never able to get it to fully work and ended up taking a different path instead. The code just became overly complicated and a new solution presented itself that was much simpler.

If anyone wants to try to tackle this, I would love to see a pull request. If not, I would like to go back and work on this eventually. It's definitely a necessary feature. Thanks for bringing it up! :smile: 

Jared

**Comment by jaredpetersen** [comment]
This is something I've been thinking about a lot lately and it's something that really should be addressed. 

I'm considering converting Codeprinter into a React application because there are some newer libraries out that help with this sort of thing and I think there is something to be gained by making the application more responsive.

I have a few other projects in the works that I'm finishing up but I think that spiffying up Codeprinter is next on the list.

**Comment by jaredpetersen** [comment]
It's been long enough.

I just started a new [branch](https://github.com/jaredpetersen/codeprinter/tree/feature-modernize-react) tonight that switches codeprinter over to React and now supports line numbers.

Still a lot to go in terms of styling of the printed code (fonts, sizes, and color schemes) and the UI but it's promising. Will keep this issue updated as I progress.

**Comment by jaredpetersen** [comment]
@srenatus Line number support has been added!

**Comment by srenatus** [comment]
@jaredpetersen awesome! 🎉 thank you for keeping on improving this.
