### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by Julix91** [jaredpetersen/codeprinter#30]
Concerns of pasting into "some website" would be reduced if it was at least served over HTTPS. 

Please consider doing that if possible.

**Comment by Julix91** [comment]
https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by jaredpetersen** [comment]
@Julix91 Done! Thanks!

**Comment by jaredpetersen** [comment]
(Still doesn't resolve the whole "you have no idea that this website isn't saving your code into a database somewhere behind the scenes" problem but I think this is the best that we can do)
