### ISSUE TITLE
Feature Request: Solidity Highlighting

### ISSUE THREAD

**Issue by ferittuncer** [jaredpetersen/codeprinter#31]
I would like Solidity language to be supported. I tried it today using GitHub highlighting option but it's not correctly highlighting it.

Solidity is a smart-contract language and smart-contracts need to be strictly reviewed so programmers often print them for review tasks. This could be really useful for many people.

**Comment by jaredpetersen** [comment]
Codeprinter uses a library for syntax highlighting. I'd recommend opening an issue with that library or adding support for it yourself.

The library is [react-syntax-highlighter](https://github.com/conorhastings/react-syntax-highlighter) and the underlying highlighting project is [hilight.js](https://github.com/highlightjs/highlight.js)

**Comment by jaredpetersen** [comment]
Nope! They are written in JavaScript but they support all the languages listed here: https://github.com/highlightjs/highlight.js/tree/master/src/languages
