### ISSUE TITLE
Feature Request: Page Numbers

### ISSUE THREAD

**Issue by ferittuncer** [jaredpetersen/codeprinter#32]
It would be very useful if printed pages would have page numbers.

**Comment by ferittuncer** [comment]
This feature is already implemented but I didn't notice at first, pressing the button with sharp sign enables it.

**Comment by jaredpetersen** [comment]
@ferittuncer Ah, I thought you meant a number a the bottom of the page that tells you what sheet of paper you're on.

The "sharp", "ocotrophe", "octothorpe", "hash", "pound", "number", etc. symbol is used to indicate line numbers as you've discovered. Sorry for the confusion.

**Comment by ferittuncer** [comment]
@jaredpetersen Actually I wanted sheet numbers because of missing line numbers. Line numbers are enough to order pages and what I wanted to be sure about page orders. If you think it is still useful, let's keep the issue open.

**Comment by jaredpetersen** [comment]
I don't have a use for it, but others may. Will re-open.

**Comment by 0xferit** [comment]
Closing this old issue as no one seems to care.
