### ISSUE TITLE
printer that print out all code at the repo

### ISSUE THREAD

**Issue by lky473736** [jaredpetersen/codeprinter#63]
it is super maybe, i think there is no program that print all code at the specific repo at github. if this skill is in this, this will be masterpiece better than now

**Comment by jaredpetersen** [comment]
Probably not something that we'd do. We'd need to be opinionated about the orderings of files, how to represent directories, skipping files... It'd also be a lot of paper.

I think this is mostly used for printing out small homework assignments. Anything more complex, you're likely looking at tools like LaTeX.

**Comment by lky473736** [comment]
alright. thanks your super program and have a nice day!
